### ISSUE TITLE
Installer doesn't detect the phone while in twrp

### ISSUE THREAD

**Issue by weegeer** [Android4Lumia950/installer#2]
![image](https://github.com/user-attachments/assets/58e4c531-db84-49d6-ad01-ce7a5f7d6171)
i was trying to install android but as soon as the phone booted to twrp the installer isnt detecting the phone. do i need drivers of sime kind or what? I just wanna give this phone a use once and for all

**Comment by toastytoaster35** [comment]
i also run the script with the .bat cause i dont know how to edit .ps1

**Comment by Kimbaras** [comment]
Hey there, 

I'm also in the same situation, basically following the readme I get up to the point 

"Device should output some print stuff then go into a black screen, you SHOULD be in LK by that point." 

Where the phone remains black, no outputs, nothing. 
I've searched the othe issue (https://github.com/Android4Lumia950/installer/issues/1) and seems we are not the only ones...
Would it be possible to know what steps were made to make it work?

Looking forward for this!
Thanks!

**Comment by djokcho** [comment]
> Hey there,
> 
> I'm also in the same situation, basically following the readme I get up to the point
> 
> "Device should output some print stuff then go into a black screen, you SHOULD be in LK by that point."
> 
> Where the phone remains black, no outputs, nothing. I've searched the othe issue (#1) and seems we are not the only ones... Would it be possible to know what steps were made to make it work?
> 
> Looking forward for this! Thanks!

**The black screen is an issue related to the fact we don't have panel support in the bootloader yet, we tried but our only way to init successfully without artifacting and framebuffer and the panel handling system is to kill the screen at init and only leave the framebuffer on if its in bootloader mode.** Tho, this scans for the reboot reason which you can either reboot to bootloader from android/twrp or the bootloader itself, then you will get output there. **For now its put on the list but it's not very important as the project has a lot going on with bugs that are way more practical to fix.**

**Comment by djokcho** [comment]
> ![image](https://private-user-images.githubusercontent.com/137427565/374590664-58e4c531-db84-49d6-ad01-ce7a5f7d6171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MzAwODcsIm5iZiI6MTczMjcyOTc4NywicGF0aCI6Ii8xMzc0Mjc1NjUvMzc0NTkwNjY0LTU4ZTRjNTMxLWRiODQtNDlkNi1hZDAxLWNlN2E1ZjdkNjE3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QxNzQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWY0NWVmYmM2MDk2MDY2YTY3ODQwNWFkNzYxNDkzN2M0NDQyYTEwZjYxMTU0MWEwNGY1ZGY0ZTcxZjRjMWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t9LLnIwONeCd_TW7ONbgpOyO5cuvFcBsOJM87OSeL7o) i was trying to install android but as soon as the phone booted to twrp the installer isnt detecting the phone. do i need drivers of sime kind or what? I just wanna give this phone a use once and for all

**This has been fixed, weeger. Check your adb and fastboot drivers and if any other drivers are conflicting!**
